import Header from "@/components/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import Animate from "@/components/Animate/Animate";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-theme="light">
      <body className={inter.className}>
        <Header></Header>
        <Animate>
          <main>{children}</main>
        </Animate>

        <Footer></Footer>
      </body>
    </html>
  );
}
